### ISSUE TITLE
get_docker_networking() matches (and thus excludes) interfaces it shouldn't

### ISSUE THREAD

**Issue by cmsj** [binhex/arch-int-vpn#41]
In tools.sh is this line:

https://github.com/binhex/arch-int-vpn/blob/623db6937ba455ba39f4793cb18e1534b321d08a/run/root/tools.sh#L52C22-L52C143

The final grep will exclude any interface with `lo` in the name, but really it should only be excluding the single interface `lo`.

Docker has the ability to name network interfaces, which can be very useful for disambiguating which interfaces are connected to which networks, for example:

```yaml
networks:
  downloaders:
    external: false
    driver: bridge
    name: downloaders
    driver_opts:
      com.docker.network.bridge.name: br-downloaders
      com.docker.network.container_iface_prefix: downloaders
```

This will result in any container attached to the `downloaders` network having an interface named `downloaders0`. You can probably see where this is going already :)

Here is what happens to the command in tools.sh with/without the final grep:

```
[root@1402fcdd8e21 /]# ip link show | grep -v 'state DOWN' | cut -d ' ' -f 2 | grep -P -o '^[^@:]+'
lo
downloaders0
[root@1402fcdd8e21 /]# ip link show | grep -v 'state DOWN' | cut -d ' ' -f 2 | grep -P -o '^[^@:]+' | grep -P -v "lo"
[root@1402fcdd8e21 /]#
```

I would suggest that a better version of that grep would be:

```
[root@1402fcdd8e21 /]# ip link show | grep -v 'state DOWN' | cut -d ' ' -f 2 | grep -P -o '^[^@:]+' | grep -P -v "^(lo|tun0)$"
downloaders0
```
